# Generated by Django 2.1.5 on 2019-02-11 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190211_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(default=datetime.datetime(2019, 2, 11, 7, 46, 55, 477881, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
